<Lesson>:
    font_size: self.height / (self.lines + 3)
    # Define the properties for the drag
    drag_rectangle: self.x, self.y, self.width, self.height
    drag_timeout: 1000
    drag_distance: 0

    markup: True

<LessonPopup>:
    size_hint: .5, .5
    title: 'Editing lesson'
    BoxLayout:
        orientation: 'vertical'
        TextInput:
            text: "Input full name/cypher"
        TextInput:
        Button:
            text: _('Accept')
            on_release: root.dismiss()
